version: '3.8'


services:
  web:
    build: .
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./reader/:/reader/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
      image: postgres:13.0-alpine
      volumes:
          - postgres_data:/var/lib/postgresql/data/
      environment:
          - POSTGRES_USER=sorryl
          - POSTGRES_PASSWORD=123
          - POSTGRES_DB=reader

volumes:
      postgres_data: