# Generated by Django 4.0.2 on 2022-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostFromUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='News')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('link', models.URLField(max_length=300, verbose_name='link')),
                ('img', models.URLField(blank=True, max_length=300, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='link')),
                ('limit', models.IntegerField(blank=True, null=True, verbose_name='Limit')),
            ],
        ),
    ]
